version: '3'
services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/home/desafio_pokemon
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
